spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sdbot-db}
    username: sdbot
    password: sdbot
    hikari:
      schema: sdbot
  flyway:
    schemas: sdbot
#server:
#  port: 8090