name: SD-bot (Master) Build, tag, create image and push image

on:
  push:
    branches: [ master ]

env:
  image_name: sdbot
  registry: ghcr.io
  registry_path: socially-disturbed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      actions: read

    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      image_url: ${{ steps.setOutput.outputs.image_url }}

    steps:
    - uses: szenius/set-timezone@v1.1
      with:
        timezoneLinux: "Europe/Oslo"
    - uses: actions/checkout@v3

    - name: Delete previous latest tag
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        tag_name: latest #(required) tag name to delete
        delete_release: true #(optional) default: true
#        repo: /<repoName> #(optional) target repository. default: repo running this action
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Bump sem-ver and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ github.token }}

    - name: Tag with latest
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ github.token }}
        custom_tag: latest
        tag_prefix: ''

    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build docker and push
      id: build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }}
        build-args: |
          project_version_arg=${{ steps.tag_version.outputs.new_tag }}  
      

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
